// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPC7S_gBoDTX0HOG93jsEYsC3IlAOnFNg',
    appId: '1:236406005665:web:85ccae8fc90cd73e9275e0',
    messagingSenderId: '236406005665',
    projectId: 'notes-flutter-18167',
    authDomain: 'notes-flutter-18167.firebaseapp.com',
    storageBucket: 'notes-flutter-18167.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4G0gyTXMW1H8LVyLaD9u12Pd7gYVZv5I',
    appId: '1:236406005665:android:3a77e96f39ff3b8e9275e0',
    messagingSenderId: '236406005665',
    projectId: 'notes-flutter-18167',
    storageBucket: 'notes-flutter-18167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAg212OKUT3PWsF6_xCp8voFKag2rvAXU',
    appId: '1:236406005665:ios:62f76c0b8b4df81e9275e0',
    messagingSenderId: '236406005665',
    projectId: 'notes-flutter-18167',
    storageBucket: 'notes-flutter-18167.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAg212OKUT3PWsF6_xCp8voFKag2rvAXU',
    appId: '1:236406005665:ios:62f76c0b8b4df81e9275e0',
    messagingSenderId: '236406005665',
    projectId: 'notes-flutter-18167',
    storageBucket: 'notes-flutter-18167.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPC7S_gBoDTX0HOG93jsEYsC3IlAOnFNg',
    appId: '1:236406005665:web:85ccae8fc90cd73e9275e0',
    messagingSenderId: '236406005665',
    projectId: 'notes-flutter-18167',
    authDomain: 'notes-flutter-18167.firebaseapp.com',
    storageBucket: 'notes-flutter-18167.firebasestorage.app',
  );
}